# Generated by Django 3.1.8 on 2021-04-21 01:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groups',
            new_name='Group',
        ),
    ]
